### PR TITLE
feat(project): update zaliql (causality)

### PR DESCRIPTION
**Pull request by CoreyCole**

### CODE REVIEW

**Comment by akcheung** [comment]
I am getting a blank page on http://db.cs.washington.edu/projects/causality/ after this merge. Is that the intent of this PR?

**Comment by CoreyCole** [comment]
No I tested locally it was working. The index.html should automatically be opened by the web browser

**Comment by CoreyCole** [comment]
http://db.cs.washington.edu/projects/causality/index.html is also not working

**Comment by CoreyCole** [comment]
https://github.com/uwdb/website/blob/cf5d2fd30278d35f80c7976b78e7bef8a42f0abf/projects/causality/index.html it is there and seems to be working, it's the other files (js/css) that are 404ing
screen shot 2018-09-14 at 12 45 58 am

But they are here in the github
screen shot 2018-09-14 at 12 46 33 am

**Comment by CoreyCole** [comment]
gh pages was not playing nicely with the single-page application. I opted to externally host and provide an external link in #60

**Comment by CoreyCole** [comment]
Thank you @akcheung

**Pull request merged**
